- template: src=start_cleaning.sh.j2 dest=/opt/start_cleaning.sh mode="u+rwx"
  become: yes

- cron: name="Clean entrance" hour=14 minute=00 job="sh /opt/start_cleaning.sh > /opt/cleaning.log"
- cron: name="Clean entrance 2" hour=10 minute=00 job="sh /opt/start_cleaning.sh > /opt/cleaning.log"
